# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sample_data.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11sample_data.proto\"\xe0\x01\n\nSampleData\x12\x13\n\x0b\x43ustomer_ID\x18\x01 \x01(\x03\x12 \n\x18\x43ustomer_Enrollment_Date\x18\x02 \x01(\x03\x12\x15\n\rCustomer_Name\x18\x03 \x01(\t\x12\x18\n\x10\x43ustomer_Address\x18\x04 \x01(\t\x12\x15\n\rCustomer_Tier\x18\x05 \x01(\t\x12\x1c\n\x14\x41\x63tive_Subscriptions\x18\x06 \x01(\t\x12\x14\n\x0c_CHANGE_TYPE\x18\x07 \x01(\t\x12\x1f\n\x17_CHANGE_SEQUENCE_NUMBER\x18\x08 \x01(\t')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sample_data_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SAMPLEDATA']._serialized_start=22
  _globals['_SAMPLEDATA']._serialized_end=246
# @@protoc_insertion_point(module_scope)
